### ISSUE TITLE
video link? number of magnets in rotor?

### ISSUE THREAD

**Issue by aewallin** [hstarmans/pcb-motor#1]
Hi, nice project! The readme has a link to a video, but it seems broken.
Found some videos on your youtube-channel, maybe you can link to one of those?

In your videos you have this coil-PCB with 6 coils, and the rotor has 4 magnets.
is that optimal? or would it work with 5 or 6 magnets also?

**Comment by hstarmans** [comment]
Video link should be fixed now.
No it is not optimal. Carl bugeja designed special magnets. He uses a metal encasing and 10 magnets see https://youtu.be/zeGKYIcLMIs?t=1186. He ordered this via ali express. The metal encasing enhances the field, this is known from pot magnets. He indeed seems to use a triangular style segment. So probably my archimedean spiral design is sub optimal.
The optimal number of magnets can be found from this document 
 https://things-in-motion.blogspot.com/2019/01/selecting-best-pole-and-slot.html
